### ISSUE TITLE
Translating to numpy etc.

### ISSUE THREAD

**Issue by juninagaki1975** [kai5z/Chladni-patterns#3]

**Comment by juninagaki1975** [comment]
I am an independent researcher in Japan.
I am quite new for FEM, it's really appreciate of your advice.

What's mean w_e and h_e in the J matrix?
h_e is high end?

**Comment by kai5z** [comment]
Hi Jun! 

w_e: width of element
h_e: height of element

Best way to learn is through books, which requires patience: 1) read into differential equations, 2) read into linear algebra, 3) read a few books on FEM

**Comment by juninagaki1975** [comment]
Hi,

Ok.
Arigatou kai5z-san.
