### ISSUE TITLE
Findinf somth Intermediate positions.

### ISSUE THREAD

**Issue by juninagaki1975** [kai5z/Chladni-patterns#4]
Hi Kai,

3) read a few books on FEM
I believe I am in here.
Struglling with practical FEM packages but just on the step of early tutorial.

I am Ubuntu 22,04, tried sfepy.
After fialed tryed Elmerfem ,
At present, each mehs viewrs are not visiblsed
 yet,It I can have your great sudjjestion, It is happily help me.

Please help me lf you know better envirnment.

Sincerely
Jun

**Comment by kai5z** [comment]
Hi! I can give no recommendations to this, most important to find something that works for you.
