### ISSUE TITLE
What's mean subscript b and s e.g. Bb Bs etc?

### ISSUE THREAD

**Issue by juninagaki1975** [kai5z/Chladni-patterns#5]
Hi Kai,

I saw D and B on textbook.
D is for material properties and B is AN, A is differential operator and N is shape function, right?

Typical formula said:
KM = int_0^L {B^T D B dx}.
without any subscripts.

May I ask about titiles issue?

Regards,
Jun

**Comment by kai5z** [comment]
Hi Jun! I do not remember off the top of my head, apologies. The book is the best teacher. I wish you all the best in sorting this out.
