### ISSUE TITLE
Patterns are a bit arranged

### ISSUE THREAD

**Issue by juninagaki1975** [kai5z/Chladni-patterns#6]
This is my first git push.
Could you please guid me to upload?

**Comment by kai5z** [comment]
Hi Jun. Would recommend looking up a tutorial by simply looking for it on google.

**Comment by juninagaki1975** [comment]
I pulled my request, thanks.

**Comment by juninagaki1975** [comment]
Because I am not sure my pull requests are well sent, please help me to know status on your side, sorry.

**Comment by kai5z** [comment]
Hi Jun! I can see no open pull requests in the repository, so apparently
something went wrong there. Should be possible to make one, though, since
there are a few pull requests approved here:

https://github.com/kai5z/Chladni-patterns/pulls

-Kai

**Comment by juninagaki1975** [comment]
Hi Kai, please confirm pull request again.

**Comment by kai5z** [comment]
Got it - Jun, please do not get me wrong, but do you know what you are
doing?

**Comment by juninagaki1975** [comment]
No, I am terribly sorry.
Isn't my code under your examination?

**Comment by kai5z** [comment]
Hi Jun. Yes, indeed, it is! So you successfully made the pull request.
Before merging the changes some comments would be needed, since I don't
understand the motivation behind these changes (please see the comments I
added to the pull request). But appreciate you contributing to this to keep
this project alive!

**Comment by juninagaki1975** [comment]
Thank you for your communication.
As I mentioned inpull request, I close this issue.

I would like to confirm reproducibility of troubles on your side.
